// Type definitions for LinksModule
// Definitions: /Users/gjosten/Projects/github-grtjn/marklogic-typescript-definitions/xml/links.xml

/**
The links module is installed as part of the Content Processing Framework.
These functions are used to manage the relationships among documents in the
database, for example, as between a binary source document and an XML document
generated by a conversion process from that source document.
The Content Processing Framework will use links to determine if related
documents should also be removed when a document is deleted from the
database. 

To use the links module as part of your own XQuery module, include the
following line in your XQuery prolog:

import module namespace lnk = "http://marklogic.com/cpf/links"
         at "/MarkLogic/cpf/links.xqy";
The library namespace prefix lnk is not predefined in
the server.
**/

declare module LinksModule {

  interface lnk {

    /** Create a link between the two given documents with the given role labels and strength. An error is raised if either of the documents involved does not exist or if the link would be invalid for some reason. This function will replace any existing link between those two documents with the new link. **/
    create(from: string, to: string, role: string, revRole: string, strength: string):  empty-sequence() ;

    /** Insert the given link. An error is raised if either of the documents involved does not exist or if the link is invalid in some way. This function will replace any existing link between those two documents. **/
    insert(link: link)):  empty-sequence() ;

    /** Remove the link between the two given documents and return the removed link. An error is raised if no such link exists. **/
    remove(from: string, to: string): link) ;

    /** Find and return the link between the two documents, if any. This function will check the properties of link and raise an error if they are inconsistent or incomplete in some way. **/
    get(from: string, to: string): link) ;

    /** Find and return all the links from the given document to some other. This function will check the properties of the link and raise an error if they are inconsistent or incomplete in some way. **/
    from(from: string): link) ;

    /** Find and return all the links to the given document from some other. This function will check the properties of the link and raise an error if they are inconsistent or incomplete in some way. **/
    to(to: string): link) ;


  }
}
